# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "6144"]
  end
  config.vm.synced_folder ".", "/vagrant"

  config.vm.network :forwarded_port, guest: 22, host: __SSH__, id: 'ssh'

  config.vm.provision "shell", inline: "sudo groupadd docker"
  config.vm.provision "shell", inline: "sudo usermod -aG docker #{USER_NAME}"
  config.vm.provision "shell", inline: "sudo sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux"
  config.vm.provision "shell", inline: "sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config"
  config.vm.provision "shell", inline: "sudo cp -r /home/#{USER_NAME}/.ssh /root/.ssh"
  config.vm.provision "shell", inline: "sudo chown -R root:root /root/.ssh"
  config.vm.provision "shell", inline: "sudo sshd restart"
  config.vm.provision "shell", inline: "systemctl disable firewalld"
  config.vm.provision "shell", inline: "systemctl stop firewalld"
end
